version: '3'

networks:
  newsblog:
services:
  newsblog-webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.server.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
    depends_on:
      - newsblog-php
      - newsblog-database
    networks:
      - newsblog
  newsblog-php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - newsblog
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./.env:/var/www/.env
      - ./artisan:/var/www/artisan
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpunit.xml:/var/www/phpunit.xml
  newsblog-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - newsblog
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
